# Generated by Django 5.2.8 on 2025-11-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='expense area', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CASH', 'Cash'), ('CITI', 'CreditCard(Citi)'), ('N26', 'N26'), ('ING', 'ING'), ('BGL', 'BGL')], default='N26', help_text='purchase method', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateinfo', models.DateField(blank=True, null=True)),
                ('place', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary', models.TextField(default='summary for spending', help_text='describe details', max_length=1000)),
                ('isfixed', models.BooleanField()),
                ('creationinfo', models.DateField(auto_now=True)),
                ('sector', models.ForeignKey(help_text='expense area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.sector')),
                ('way', models.ForeignKey(help_text='choose a method', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.way')),
            ],
            options={
                'ordering': ['-dateinfo', 'creationinfo', 'sector'],
            },
        ),
    ]
